name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        working-directory: ./part11-cicd/fs-pokedex
        run: npm install
      - name: Lint code
        working-directory: ./part11-cicd/fs-pokedex
        run: npm run eslint